tes: change deploiy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,8 +24,22 @@ jobs:
         with:
           python-version: "3.x"
 
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install csv
+
       - name: Run Python script
-        run: python generate_css_rules.py
+        run: |
+          python generate_css_rules.py
+          cat generated_rules.css  # Affiche le contenu du fichier généré pour vérification
+
+      - name: Verify CSS file
+        run: |
+          if [ ! -f generated_rules.css ]; then
+            echo "Error: generated_rules.css was not created"
+            exit 1
+          fi
 
       - name: Setup Pages
         uses: actions/configure-pages@v4
